package com.ihcl.qwikcilver.model

data class ConfigParameters(
    val qcBaseUrl: String,
    val woohooBaseUrl: String,
    val qcTransactionId:String,
    val qcUserName: String,
    val woohooUserName: String,
    val qcPassword: String,
    val woohooPassword: String,
    val reloadTerminalId: String,
    val reloadUserName: String,
    val reloadPassword: String,
    val qcTerminalId: String,
    val qcMerchantOutletNameToOverride: String,
    val woohooClientId: String,
    val woohooClientSecret: String,
    val woohooCatalogue_username: String,
    val woohooCatalogue_password:String,
    val memberEnrollmentURL:String,
    val gravityHeaderKey:String,
    val authorizationKey:String,
    val authorizationCode: String,
    val epicureHeaderCode:String,
    val createMembershipPlan:String,
    val memberLookUp:String,
    val availPrivilege:String,
    val getPrivilege:String,
    val bitCancellationVoucher:String,
    val getLoyaltyPointsUrl: String,
    val tataNeuClient_Id: String,
    val tataNeuStore_Id: String,
    val redeemNeuCoinsUrl: String,
    val reverseNeuCoins:String,
    val partnerId:String,
    val loyaltyTransactionHistoryURL:String,
    val connectionString:String,
    val databaseName:String,
    val gravtyUserName:String,
    val gravtyPassWord:String,
    val gravtyTokenURL:String,
    val memberEnrollmentLoggedIn:String,
    val memberLookUpValidationURL:String,
    val gravtyMemberCardsURL:String,
    val gravtyFetchMemberShip:String,
    val chambersHeaderKey:String,
    val epicurePrimaryCard:String,
    val gravtyEpicurePassWord:String,
    val gravtyChamberPassWord:String,
    val epicureProgramId:String,
    val chamberProgramId:String,
    val gravtySponserId:String,
    val redisKey:String,
    val redisHost:String,
    val redisPort:String,
    val gcCatalogueTTL:String,
    val requestTimeoutMillis:String,
    val connectionPoolMinSize: String,
    val connectionPoolMaxSize: String,
    val gravtyBenefitsCarousel:String,
)
data class AuthToken (
    val token:String?,
    val expires_in:String?
)